version: '3'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - /home/ael-mezz/data/html:/var/www/html
    networks:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    volumes:
      - /home/ael-mezz/data/html:/var/www/html
    networks:
      - wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/ael-mezz/data/mysql:/var/lib/mysql
    networks:
      - wordpress
    env_file: 
      - .env

networks:
  wordpress:
    driver: bridge

volumes:
  v_database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ael-mezz/data/mysql'
  v_wordpress-ngnix:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ael-mezz/data/html'